project:
  type: website
  output-dir: docs
  
website:
  title: "LInC Lab"
  navbar:
    background: light
    logo: "img/icon-512.png"
    left:
      - file: index.qmd
        text: About
      - file: people.qmd
        text: People
      - file: publications.qmd
        text: Publications
      - file: contact.qmd
        text: Contact

format:
  html:
    theme: litera
    css: styles.css
    toc: true



