project:
  type: website
  output-dir: docs
  
website:
  title: "LInC Lab"
  page-footer: "Copyright 2022. Rachel Ryskin" 
  navbar:
    background: light
    logo: "img/icon-512.png"
    left:
      - file: index.qmd
        text: About
      - file: people.qmd
        text: People
      - file: research.qmd
        text: Research
      - file: contact.qmd
        text: Contact

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    mainfont: sans-serif



