# Open Positions

## Lab Manager/Research Technician

The Language, Interaction, & Cognition (LInC) Lab at University of California, Merced (PI: Rachel Ryskin) invites applications for a full-time Lab Assistant position to begin in Summer or Fall 2024 (start date flexible). We are looking for applicants interested in studying cognition and language using behavioral, neuroscientific, and computational methods. Please see https://linclab0.github.io/ for more on our work.

The position is for one year with a possibility of renewal. The ideal candidate will be interested in ultimately pursuing graduate study in cognitive science, psychology, linguistics, neuroscience, data science, or a related field. The successful candidate will have primary or shared responsibility for various aspects of research and laboratory management, including: creating experimental stimuli; coding/transcribing data; designing experiments; programming experiments; collecting data from various participant populations; pre-processing and analyzing data; helping manage the lab's computers and server; and assisting undergraduate and graduate researchers. The successful candidate will work closely with Dr. Ryskin and with other research assistants and graduate students in the lab. The position is an excellent opportunity to gain multidisciplinary research experience.

The following qualifications are essential:

- Bachelor’s degree or equivalent in cognitive science, psychology, data science, computer science, linguistics, neuroscience, statistics, mathematics, engineering or related field
- Excellent organizational skills and a high level of attention to detail
- Excellent interpersonal communication skills and experience working on a team
- Strong programming, statistical, and/or web development skills (e.g. Python, R, Javascript, Matlab, etc.)
- Prior research experience and knowledge of research principles in cognitive science, psychology, neuroscience, or related field

The following qualifications are desirable but not required:

- Prior experience with data science methods (e.g., web scraping, data cleaning and manipulation, machine learning, and natural language processing)
- Prior experience with analysis of behavioral and/or neural data

To apply for the position, please complete the application below.

Submissions will be reviewed on a rolling basis and continue until the position is filled. We will begin reviewing applications on June 1st, 2024.


If you have any questions about the position or the application process, please send an email to [linc.lab.ucmerced@gmail.com](mailto:linc.lab.ucmerced@gmail.com).

### Application

Please send your CV and answers to the below questions to [linc.lab.ucmerced@gmail.com](mailto:linc.lab.ucmerced@gmail.com). Please send these in the format “Lastname_CV.pdf” and “Lastname_application.pdf” in an email with the subject line, “Lastname Lab Manager Position 2024”.

1. Please provide the following information:
  
    a)   Telephone

    b)   Email
  
    c)   Current city of residence

    d)   Undergraduate institution

    e)   Undergraduate major(s)

    f) 	Cumulative GPA

    g)   Year of graduation or expected graduation
  
    h)   Are you eligible to work in the US? (unfortunately, we are unable to sponsor new work visas for international applicants)
  
2. What experience do you have with empirical research? On what kind of studies did you work (e.g., mTurk, laboratory studies, neuroimaging studies, analysis of big datasets, other)? In what way(s) were you involved in this work (e.g., did you design the study, schedule and run participants, analyze data, program the experiment, etc.)?

3. Please comment on your programming and technical expertise. What programming languages have you used (e.g., Matlab, Python, Bash, HTML/CSS, Javascript, PHP, MySQL)? Could you program an experiment, for example, in PsychoPy, Psychtoolbox, or another software package? Do you have any experience with database development/management? Have you worked with machine learning or NLP methods?

4. Please comment on your statistical expertise. What kinds of analyses are you comfortable implementing? What statistical analysis packages do you have experience with (e.g. SPSS, R, etc.)? Do you have any experience with computational modeling?

5. What are your long-term goals? How will this job help you reach those goals?

6. How long do you plan to stay in this job?

7. In this job, you would be involved in many different kinds of tasks that differ in the skills that they demand. No one is likely to have all these skills on the first day of the job, which is fine; that’s what learning is for. Here are some descriptions of different tasks, demands, and skills that the job will sometimes require. Please rank-order these from those that you are most to least comfortable with:

   	- Attention to detail
   	- Writing
   	- Programming
   	- Tolerance for sometimes repetitive work
   	- Interacting with other people
   	- Managing other people
   	- Organizing large quantities of information
   	- Independence (e.g., the ability to figure something hard out on your own)
   	- Working against a deadline
 
 
8. Which [research](research.qmd) project from the lab are you most interested in exploring and why? 

9. If you are able to share links to any examples of your technical work (e.g. on GitHub or a personal website) please include them here.

10. Please provide the contact information for at least two individuals who could be asked for a recommendation and indicate in what capacity you have worked with them, and for how long.
 

